# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20170210_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.085, max_digits=50),
        ),
    ]
